name: todo-app
services:
  frontend:
    image: node:24.1-bookworm-slim #Node.js 24.1（Debian Bookwormベースの軽量イメージ）をベースにしています。
    working_dir: /container/todo-app-frontend #作業ディレクトリを/containerに設定します。以降のコマンドはこのディレクトリ内で実行されます。
    volumes:
      - ./frontend/container:/container #コンテナ外の./frontend/containerとコンテナ内の/containerを同期
    ports:
      - "3000:3000" # nextjsでの開発用ローカルサーバのポート
      - "3001:3001" # json-serverで開発用の一時サーバー(DBの代わり)を使うためのポート
      - "6006:6006" # storybookでのストーリー確認サイト立ち上げのためのポート
    command: sh -c "npm install && npx playwright install --with-deps && npm run dev:all" # js依存関係install && playwrightブラウザ情報install && 開発用サーバー立ち上げ

  backend:
    image: node:24.1-bookworm-slim
    working_dir: /app
    volumes:
      - ./backend/app:/app
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run dev"
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/todo_db
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "7777:80" # ホストの7777ポートをnginxコンテナの80ポートにマッピング
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # nginx設定ファイルを読み取り専用でマウント
    depends_on:
      - frontend
      - backend

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  llm-api:
    build: ./llm-scheduler/api
    working_dir: /app
    volumes:
      - ./llm-scheduler/api:/app
    ports:
      - "8080:8080"
    depends_on:
      - ollama

  playwright:
    image: mcr.microsoft.com/playwright:v1.53.2-noble
    working_dir: /tests
    ports:
      - "9323:9323" # playwrightレポート用
    volumes:
      - ./frontend/container/todo-app-frontend/e2e:/tests
      - ./frontend/container/todo-app-frontend/playwright-report:/tests/playwright-report
      - ./frontend/container/todo-app-frontend/test-results:/tests/test-results
    depends_on:
      - nginx
    command: sh -c "npm install &&  tail -f /dev/null"
    env_file:
      - ./frontend/container/todo-app-frontend/.env

volumes:
  mysql-data:
  ollama-data:
