name: todo-app
services:
  frontend:
    image: node:24.1-bookworm-slim #Node.js 24.1（Debian Bookwormベースの軽量イメージ）をベースにしています。
    working_dir: /app #作業ディレクトリを/containerに設定します。以降のコマンドはこのディレクトリ内で実行されます。
    volumes:
      - ./frontend/app:/app #コンテナ外の./frontend/containerとコンテナ内の/containerを同期
    ports:
      - "3000:3000" # Next.js開発サーバー
      - "3001:3001" # json-server用（必要なら）
      - "6006:6006" # storybook用
    command: sh -c "npm install && npm run dev:all"

  backend:
    image: node:24.1-bookworm-slim
    working_dir: /app
    volumes:
      - ./backend/app:/app
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run dev"
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/todo_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
