name: todo-app
services:
  frontend:
    image: node:24.1-bookworm-slim #Node.js 24.1（Debian Bookwormベースの軽量イメージ）をベースにしています。
    working_dir: /container/todo-app-frontend #作業ディレクトリを/containerに設定します。以降のコマンドはこのディレクトリ内で実行されます。
    volumes:
      - ./frontend/container:/container #コンテナ外の./frontend/containerとコンテナ内の/containerを同期
    ports:
      - "3000:3000" # nextjsでの開発用ローカルサーバのポート
      - "3001:3001" # json-serverで開発用の一時サーバー(DBの代わり)を使うためのポート
      - "6006:6006" # storybookでのストーリー確認サイト立ち上げのためのポート
    command: sh -c "npm install && npm run dev:all"

  backend:
    image: node:24.1-bookworm-slim
    working_dir: /app
    volumes:
      - ./backend/app:/app
    ports:
      - "4000:4000" # ローカルから直接リクエストできるようにする窓口
    env_file:
      - ./backend/app/.env # docker composeは置いてある.envを自分のものにしてプロセスに公開しないので、明示して公開させる
    command: sh -c "npm install && npm run dev"
